name: Deploy LetCode in FireBase

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install
        working-directory: test-workflows

      - run: npm run build
        working-directory: test-workflows

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//03GlgnmwZc-Z_CgYIARAAGAMSNwF-L9Ir4uZSdRKMyD51gKNs-WHUrxpnfGfnvbkXR4yuMOaUiTKNibJK6-UYAZlkRRidZQHLjvo
          PROJECT_ID: "chrome-extension-21f92"
